// Response Error Code
export enum AppErrorCode {
  INTERNAL_SERVER_ERROR = '500',
  PRISMA_ERROR = '301',
  HEADERS_INVALID = '405',
  VALIDATION_ERROR = '406',
  USER_STATUS_NOT_FOUND = '411',
  APPLICATION_NOT_FOUND = '422',
  USER_MODULE_NOT_FOUND = '433',
}
